apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i9bhd3faf-go 
  janus-idp.io/tekton: i9bhd3faf-go
  backstage.io/kubernetes-id: i9bhd3faf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i9bhd3faf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml